const
    WEATHER_RAINY_COUNTRYSIDE = 16
    WEATHER_CLOUDY_COUNTRYSIDE = 15

    WEATHER_CLOUDY_SF = 7
    WEATHER_RAINY_SF = 8

    WEATHER_CLOUDY_LS = 4

    WEATHER_CLOUDY_LV = 12

    WEATHER_SANDSTORM = 19
end